### ISSUE TITLE
xst echoes "near "update": syntax error" error randomly?

### ISSUE THREAD

**Issue by tmpm697** [gnotclub/xst#101]
I currently have this issue that I can't trace.

sometimes (randomly) my terminal (xst / 1:0.8.4.r0.gda50afd-1) echo below error:
```
Error: near line 624: near "update": syntax error
```
with the number `624` will appear randomly (like 1332, 3433)

through my `zsh` env, I don't have any `update` function.

**Comment by actionless** [comment]
but does this reproducible in bash or fish, ie in scenario where zsh not involved at all?

**Comment by tmpm697** [comment]
I got the issue, it's not related to xst.
