### ISSUE TITLE
can't launch with rofi

### ISSUE THREAD

**Issue by arkhan** [gnotclub/xst#102]
Greetings, with the last update when trying to launch with rofi I have the following error:

```
Couldn't set window size: Inappropriate ioctl for device
write error on tty: Bad file descriptor
```

Thansks

**Comment by neeasade** [comment]
weird -- I have the same issue with `rofi -show run`, but not with `dmenu_path | rofi -dmenu`

**Comment by neeasade** [comment]
note: other repro:

``` sh
# works:
$ xst

# fails
$ echo | xst
Couldn't set window size: Inappropriate ioctl for device
```

**Comment by kxc0re** [comment]
seems like im running into a similiar issue

can't start it via sxhkd on system startup, 
after restarting sxhkd manually it magically works again

**Comment by neeasade** [comment]
Thanks for reporting.
