### ISSUE TITLE
neovim crash

### ISSUE THREAD

**Issue by carlitos777** [gnotclub/xst#106]
Hi guys,
When I asked for an upgrade back in January, I couldn't imagine how far we would get... thanks for all collaborators.
However when I try to launch neovim it always crashes, getting error message like:

~ % nvim
ABORT: lookup_next within a TYPE_KEY node
[1]    1225 abort (core dumped)  nvim

journalctl:

systemd-coredump[1228]: Process 1225 (nvim) of user 1000 dumped core.

                                              Stack trace of thread 1226:
                                              #0  0x00007f796781e355 raise (libc.so.6 + 0x3c355)
                                              #1  0x00007f7967807853 abort (libc.so.6 + 0x25853)
                                              #2  0x00007f7967743df4 n/a (libtermkey.so.1 + 0x6df4)
                                              #3  0x00007f7967744145 n/a (libtermkey.so.1 + 0x7145)
                                              #4  0x00007f7967740b35 termkey_start (libtermkey.so.1 + 0x3b35)
                                              #5  0x0000562b72e5d020 tinput_init (nvim + 0xa6020)
                                              #6  0x0000562b72e6650e n/a (nvim + 0xaf50e)
                                              #7  0x00007f7967770422 start_thread (libpthread.so.0 + 0x9422)
                                              #8  0x00007f79678e1bf3 __clone (libc.so.6 + 0xffbf3)

                                              Stack trace of thread 1225:
                                              #0  0x00007f7967776e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                              #1  0x00007f79677a654a uv_cond_wait (libuv.so.1 + 0x1d54a)
                                              #2  0x0000562b72e5ac5c ui_bridge_attach (nvim + 0xa3c5c)
                                              #3  0x0000562b72e1f297 main (nvim + 0x68297)
                                              #4  0x00007f7967809002 __libc_start_main (libc.so.6 + 0x27002)
                                              #5  0x0000562b72e1fdce _start (nvim + 0x68dce)
-- Subject: Process 1225 (nvim) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
--
-- Process 1225 (nvim) crashed and dumped core.
--
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.

I am on archlinux, with latest aur xst-git package. I am a zsh fanatic but switching to bash produces the same error.
Any idea?

Thanks,

carlitos

**Comment by neeasade** [comment]
temp workaround: `TERM=xterm nvim` -- related nvim issue: https://github.com/neovim/neovim/issues/5895

**Comment by carlitos777** [comment]
Yes, thanks, I did find referenced neovim issue, but unfortunately I am not an st expert, so I am not able to generate a new terminfo (via tic -sx st.info) 

my infocmp -L:

xst-256color| simpleterm with 256 colors,
        auto_right_margin, back_color_erase, can_change,
        eat_newline_glitch, has_status_line, move_insert_mode,
        move_standout_mode, no_pad_char,
        columns#80, init_tabs#8, lines#24, max_colors#0x100,
        max_pairs#0x7fff,
        acs_chars=+C\054D-A.B0E``aaffgghFiGjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        back_tab=\E[Z, bell=^G, carriage_return=\r,
        change_scroll_region=\E[%i%p1%d;%p2%dr,
        clear_all_tabs=\E[3g, clear_screen=\E[H\E[2J,
        clr_bol=\E[1K, clr_eol=\E[K, clr_eos=\E[J,
        column_address=\E[%i%p1%dG,
        cursor_address=\E[%i%p1%d;%p2%dH, cursor_down=\n,
        cursor_home=\E[H, cursor_invisible=\E[?25l,
        cursor_left=^H, cursor_normal=\E[?12l\E[?25h,
        cursor_right=\E[C, cursor_up=\E[A,
        cursor_visible=\E[?25h, delete_character=\E[P,
        delete_line=\E[M, ena_acs=\E)0,
        enter_alt_charset_mode=\E(0, enter_blink_mode=\E[5m,
        enter_bold_mode=\E[1m, enter_ca_mode=\E[?1049h,
        enter_dim_mode=\E[2m, enter_insert_mode=\E[4h,
        enter_italics_mode=\E[3m, enter_reverse_mode=\E[7m,
        enter_secure_mode=\E[8m, enter_standout_mode=\E[7m,
        enter_underline_mode=\E[4m, erase_chars=\E[%p1%dX,
        exit_alt_charset_mode=\E(B,
        exit_attribute_mode=\E[0m, exit_ca_mode=\E[?1049l,
        exit_insert_mode=\E[4l, exit_italics_mode=\E[23m,
        exit_standout_mode=\E[27m,
        exit_underline_mode=\E[24m,
        flash_screen=\E[?5h$<80/>\E[?5l, from_status_line=^G,
        init_2string=\E[4l\E>\E[?1034l,
        initialize_color=\E]4;%p1%d;rgb\072%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\,
        insert_line=\E[L, key_a1=\E[1~, key_a3=\E[5~,
        key_b2=\EOu, key_backspace=^H, key_btab=\E[Z,
        key_c1=\E[4~, key_c3=\E[6~, key_clear=\E[3;5~,
        key_dc=\177~, key_dl=\E[3;2~, key_down=\EOB,
        key_eic=\E[2;2~, key_end=\E[4~, key_enter=\EOM,
        key_eol=\E[1;2F, key_eos=\E[1;5F, key_f1=\EOP,
        key_f10=\E[21~, key_f11=\E[23~, key_f12=\E[24~,
        key_f13=\E[1;2P, key_f14=\E[1;2Q, key_f15=\E[1;2R,
        key_f16=\E[1;2S, key_f17=\E[15;2~, key_f18=\E[17;2~,
        key_f19=\E[18;2~, key_f2=\EOQ, key_f20=\E[19;2~,
        key_f21=\E[20;2~, key_f22=\E[21;2~, key_f23=\E[23;2~,
        key_f24=\E[24;2~, key_f25=\E[1;5P, key_f26=\E[1;5Q,
        key_f27=\E[1;5R, key_f28=\E[1;5S, key_f29=\E[15;5~,
        key_f3=\EOR, key_f30=\E[17;5~, key_f31=\E[18;5~,
        key_f32=\E[19;5~, key_f33=\E[20;5~, key_f34=\E[21;5~,
        key_f35=\E[23;5~, key_f36=\E[24;5~, key_f37=\E[1;6P,
        key_f38=\E[1;6Q, key_f39=\E[1;6R, key_f4=\EOS,
        key_f40=\E[1;6S, key_f41=\E[15;6~, key_f42=\E[17;6~,
        key_f43=\E[18;6~, key_f44=\E[19;6~, key_f45=\E[20;6~,
        key_f46=\E[21;6~, key_f47=\E[23;6~, key_f48=\E[24;6~,
        key_f49=\E[1;3P, key_f5=\E[15~, key_f50=\E[1;3Q,
        key_f51=\E[1;3R, key_f52=\E[1;3S, key_f53=\E[15;3~,
        key_f54=\E[17;3~, key_f55=\E[18;3~, key_f56=\E[19;3~,
        key_f57=\E[20;3~, key_f58=\E[21;3~, key_f59=\E[23;3~,
        key_f6=\E[17~, key_f60=\E[24;3~, key_f61=\E[1;4P,
        key_f62=\E[1;4Q, key_f63=\E[1;4R, key_f7=\E[18~,
        key_f8=\E[19~, key_f9=\E[20~, key_home=\E[1~,
        key_ic=\E[2~, key_il=\E[2;5~, key_left=\EOD,
        key_mouse=\E[M, key_npage=\E[6~, key_ppage=\E[5~,
        key_right=\EOC, key_sdc=\E[3;2~, key_send=\E[1;2F,
        key_sf=\E[1;2B, key_shome=\E[1;2H, key_sic=\E[2;2~,
        key_sleft=\E[1;2D, key_snext=\E[6;2~,
        key_sprevious=\E[5;2~, key_sr=\E[1;2A,
        key_sright=\E[1;2C, key_up=\EOA,
        keypad_local=\E[?1l\E>, keypad_xmit=\E[?1h\E=,
        orig_colors=\E]104^G, orig_pair=\E[39;49m,
        parm_dch=\E[%p1%dP, parm_delete_line=\E[%p1%dM,
        parm_down_cursor=\E[%p1%dB, parm_ich=\E[%p1%d@,
        parm_index=\E[%p1%dS, parm_insert_line=\E[%p1%dL,
        parm_left_cursor=\E[%p1%dD,
        parm_right_cursor=\E[%p1%dC, parm_rindex=\E[%p1%dT,
        parm_up_cursor=\E[%p1%dA, print_screen=\E[i,
        prtr_off=\E[4i, prtr_on=\E[5i, reset_1string=\Ec,
        reset_2string=\E[4l\E>\E[?1034l, restore_cursor=\E8,
        row_address=\E[%i%p1%dd, save_cursor=\E7,
        scroll_forward=\n, scroll_reverse=\EM,
        set_a_background=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        set_a_foreground=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        set_attributes=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        set_background=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        set_foreground=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        set_tab=\EH, tab=^I, to_status_line=\E]0;,

Not working:

key_b2=\EOu, key_backspace=^H, key_btab=\E[Z,
key_dc=\177~, key_dl=\E[3;2~, key_down=\EOB,

Working:

key_b2=\EOu, key_backspace=\177, key_btab=\E[Z,
key_dc=\E[3~, key_dl=\E[3;2~, key_down=\EOB,

Thanks

**Comment by actionless** [comment]
@carlitos777 
does this help? https://github.com/gnotclub/xst/pull/109

**Comment by carlitos777** [comment]
**@actionless**
YES, it defitinely does, thanks for this, hope to see it merged asap.

**Comment by actionless** [comment]
thanks for the quick feedback!
