### ISSUE TITLE
Weird window border color?

### ISSUE THREAD

**Issue by tmpm697** [gnotclub/xst#110]
Relate to this issue https://github.com/gnotclub/xst/issues/82, in this [comment](https://github.com/gnotclub/xst/issues/82#issuecomment-653828497), issue's closed so I create new focused one.

I have this issue with:
```
xst-git: 1:0.8.4.r9.g079cf8c-1
OS: archlinux up-to-date
```

**Comment by actionless** [comment]
and which WM do you use?

**Comment by tmpm697** [comment]
I don't use window manager, just start X and using `wmutils` and other utils to work with windows.

**Comment by actionless** [comment]
how could it be any window border then if st doesn't have CSD

**Comment by actionless** [comment]
or you mean you using some util for drawing borders -- in that case check with openbox first, if you can't reproduce it there, report a bug in that border drawing util

**Comment by neeasade** [comment]
Just played with it -- The fix for this for me was to force window depth to be 24 (for window drawing utilities from wmutils and my own opt) -- right now the default is to inherit from the root window. I'll PR a flag to override it for people who encounter this.
