### ISSUE TITLE
Resizing font reverts to default font

### ISSUE THREAD

**Issue by nikp123** [gnotclub/xst#114]
The issue is quite simple: When I set the font in the .Xresources file, it applies it initially, however when I try to resize the font using the keyboard shortcuts (Ctrl+Shirt+Pg.Up/Down) it reverts to the default Liberation Sans font (or any font that is hardcoded in the config.h file)

**Comment by actionless** [comment]
was broken in f0706451f234a3db8a6a4e6b4471b174ced3f084

**Comment by actionless** [comment]
after move investigation, it seems what the mentioned commit just unveiled the problem, which was in previous design, preparing a patch

**Comment by actionless** [comment]
@nikp123 please try with this patch: https://github.com/gnotclub/xst/pull/115/files

**Comment by nikp123** [comment]
@actionless confirmed working
