### ISSUE TITLE
Implement clickable links

### ISSUE THREAD

**Issue by tmplt** [gnotclub/xst#12]
`xst` does everything I want it too, except that I can't click links to open them in my browser (from what I can find). Could this be implemented?

**Comment by neeasade** [comment]
I consulted suckless irc for tips concerning such, will see if I can locate the log later.

**Comment by neeasade** [comment]
also FWIW if you hadn't seen, currently `alt + u` is bound to launch dmenu with urls currently in the window, selected url opens with `$BROWSER`.

**Comment by Tmplt** [comment]
>I consulted suckless irc for tips concerning such, will see if I can locate the log later.

Cheers

>alt + u is bound to launch dmenu with urls currently in the window, selected url opens with $BROWSER.

I was wondering what spawned that; thanks. You might want to add `xurls` to the PKGBUILD.

**Comment by neeasade** [comment]
I couldn't locate those logs, maybe I didn't save them after all : (

**Comment by pellettiero** [comment]
Could this be useful?
http://st.suckless.org/patches/copyurl
Looks like a patch to select and copy previously displayed URLs (in C) which I suppose could be piped in `dmenu` without `perl` or `go` dependencies.

**Comment by neeasade** [comment]
Hi -- yepp that's currently done in bindings, for clicking the issue is not so much parsing the current window but rather getting current text that's directly under the cursor. as mentioned above for now alt + u is bound to `xurls | eval dmenu $(dmenu_options) | xargs -r $BROWSER" `

**Comment by pellettiero** [comment]
Well then, maybe it's best to include the script in the PKGBUILD if using the `perl` version of `xurls`, or the release compiled version of `xurls` if using the `go` version from the AUR, this way you don't have to install another dependency.

Thanks!

**Comment by neeasade** [comment]
oh you mean add as optional dependency? yeah that would probably be a good idea. (personally I use the go xurls)

**Comment by pellettiero** [comment]
Yeah, the problem is that the PKGBUILD of the go version _needs_ go to build, when there's already compiled versions on Github.

Better use the precompiled binaries, no?
We'll have to let the maintainer know and tell him to make 2 repos `xurls` and `xurls-git`, it's way better :)

**Comment by neeasade** [comment]
Deciding not to support clickable links unless it comes down from st (or maybe if there is a suckless accepted patch)
