### ISSUE TITLE
Truecolor not working.

### ISSUE THREAD

**Issue by crdpa** [gnotclub/xst#123]
I use the amfora browser to navigate through gemini sites and it needs a terminal which supports truecolor to render the theme correctly. I heard st supports truecolor, so xst should support too. But it is not working.

Using the alacritty terminal i have the exactly colors i want, but it is not happening with xst.

Here is a picture: ![1123-2](https://user-images.githubusercontent.com/61637474/100013810-36b31000-2db4-11eb-8674-61b026443c7e.png)

xst is on the left side of the screen, alacritty is on the right. Amfora is open on both. I defined the background on amfora to be the same as the terminal (dracula theme), but xst renders it as another color. This happens with terminals which don't support truecolor. It is what was happening to me with urxvt.

Is there any setting i need to put in the config file?

This happens with the kakoune text editor too.

**Comment by neeasade** [comment]
What is your $TERM? it should be xst-256color, with the terminfo file
installed (which should happen by default depending on how you installed
xst) -- see: https://github.com/gnotclub/xst/blob/master/st.info#L212

Thanks,
Nathan

**Comment by crdpa** [comment]
echo $TERM gives me xst-256color

**Comment by hackedWifi** [comment]
> echo $TERM gives me xst-256color
> 
> It needs the st-terminfo installed? Void linux doesn't pull it as a dependency.
> 
> Found this file. Is this it? /usr/share/terminfo/x/xst.terminfo

I have that file on that directory, and true color is not consistent with st. I can't get nova colors to display correctly. The background color is brighter on xst than that is on st. Both are loading colors from .Xresources

**Comment by actionless** [comment]
could you provide an actual testcase, like `printf "smth"`, and screenshots how it works in st and how is broken here?

**Comment by neeasade** [comment]
Confirmed truecolor working in st with a truecolor theme in terminal emacs (emacs didn't know of xst-256color, so I had to hint by eg `COLORTERM=truecolor emacs -nw`)
