### ISSUE TITLE
neovim not opening 

### ISSUE THREAD

**Issue by siduck76** [gnotclub/xst#125]
ive been using xst so far but why neovim doesnt open with it now , st on the right , xst left
![image](https://user-images.githubusercontent.com/59060246/101132760-894ec080-362d-11eb-8599-7dfb52cb7fe9.png)

**Comment by actionless** [comment]
mb again some quirks with your font?

![2020-12-04--1607075256_953x1040_scrot](https://user-images.githubusercontent.com/1655669/101148812-61a42c00-361e-11eb-8ff2-c5ec09b89309.png)

**Comment by siduck76** [comment]
I think no , Ive been using xst for months now and that never messed up nvim but idk how it borked today , if I remove xst package ( im on void ) then the issue fixes up but then the backspace key doesnt work at all :(

**Comment by actionless** [comment]
then contact the maintainer of the void package you're using, it does smth weird with terminfo

**Comment by dotnetfox** [comment]
@siduck76 please update xst on void, no terminfo compilation errors should appear now.

**Comment by Arrow-x** [comment]
This happens from both AUR packages too

**Comment by siduck** [comment]
> @siduck76 please update xst on void, no terminfo compilation errors should appear now.

i no longer use xst
