### ISSUE TITLE
no transparency

### ISSUE THREAD

**Issue by ndowens** [gnotclub/xst#126]
https://termbin.com/7kz8

xst 0.8.4 with the above setting gives no transparency. I am using plasma with compositor enabled, opengl.
Brought to my attention originally by https://github.com/void-linux/void-packages/issues/27070

**Comment by vikigenius** [comment]
This is broken by the latest update i think. It worked just before the recent update.

**Comment by ndowens** [comment]
> This is broken by the latest update i think. It worked just before the recent update.

Yup, just tested older version and it works with 0.7.2

**Comment by vikigenius** [comment]
@ndowens, can you test if blinking cursors work for you in 0.8.4 ? I think the recent update broke that as well https://github.com/gnotclub/xst/issues/127

**Comment by ndowens** [comment]
With 0.7.2 mine doesn't blink either

**Comment by vikigenius** [comment]
@ndowens  Hmm, mine does blink in 0.7.2 if i set:
 
```
st.cursorshape:       1
st.cursorthickness:   2
st.cursorblinkstyle:  0
st.cursorblinkontype: 1
st.blinktimeout:      800
```

**Comment by ndowens** [comment]
Hoping this gets resolved, or I will just revert to older version after giving sometime

**Comment by vikigenius** [comment]
master seems to be working just fine. Maybe it's time to just update to a new release version?

**Comment by ndowens** [comment]
> master seems to be working just fine. Maybe it's time to just update to a new release version?

Will have to figure out which of the changes in master fixed the issue so can use it as a patch

**Comment by actionless** [comment]
> some of the option names changed, make sure you are in-sync with example .Xresources config (https://github.com/gnotclub/xst/blob/master/.Xresources)

> if smth still doesn't work, paste here the output of `xrdb -q | grep '^st.'` and diff of your `config.h` with `config.h.def` in case if you made there any changes as well

particularly with transparency there are 2 new options now, `st.disable_alpha_correction` and `st.depth` which both could affect the final result

**Comment by actionless** [comment]
also reports for not latest git master are not accepted

**Comment by ndowens** [comment]
> also reports for not latest git master are not accepted

Then I don’t see point of releases if those won’t get support?

**Comment by actionless** [comment]
feel free to assign yourself to support them, @ndowens

**Comment by ndowens** [comment]
@vikigenius i will figure out which commit fixes it and I will orphan it if you want it

**Comment by actionless** [comment]
in that case, i can create 0.8.x branch and you could maintain it if you like, @ndowens 

and new features we would do as now on master, and they will be release as 0.9-smth

sounds fine for you @neeasade ?

**Comment by neeasade** [comment]
I think a new release is fair given the decisions that were made after
tagging 0.8.4 - let's tag 0.8.4.1.

(Also hello void users! I was afk yesterday evening)

**Comment by ndowens** [comment]
Thanks for new release
