### ISSUE TITLE
0.8.4 breaks cursor blinking

### ISSUE THREAD

**Issue by vikigenius** [gnotclub/xst#127]
void linux recently updated xst to version 0.8.4
This breaks cursor blinking and transparency: https://github.com/gnotclub/xst/issues/126

**Comment by actionless** [comment]
some of the option names changed, make sure you are in-sync with example .Xresources config (https://github.com/gnotclub/xst/blob/master/.Xresources)

if smth still doesn't work, paste here the output of `xrdb -q | grep '^st.'` and diff of your `config.h` with `config.h.def` in case if you made there any changes as well

**Comment by vikigenius** [comment]
@actionless 

Here you go:

```
st.background:  #1e2029
st.blinktimeout:        800
st.disablebold:   1
st.borderpx:    10
st.chscale:     1.0
st.color0:      #1e2029
st.color1:      #cf6a4c
st.color10:     #8f9d6a
st.color11:     #f9ee98
st.color12:     #7587a6
st.color13:     #9b859d
st.color14:     #afc4db
st.color15:     #f8f8f2
st.color16:     #cda869
st.color17:     #9b703f
st.color18:     #323537
st.color19:     #464b50
st.color2:      #4f9c69
st.color20:     #838184
st.color21:     #c3c3c3
st.color3:      #cda869
st.color4:      #7587a6
st.color5:      #9b859d
st.color6:      #afc4db
st.color7:      #a7a7a7
st.color8:      #5f5a60
st.color9:      #cf6a4c
st.cursorblinkontype:   1
st.cursorblinkstyle:    0
st.cursorshape: 1
st.cursorthickness:     2
st.cwscale:     1.0
st.font:        SauceCodePro Nerd Font Mono:pixelsize=20
st.foreground:  gray
st.opacity:     200
st.scrollrate:  1
st.shell:       /bin/zsh
st.termname:    st-256color
```

I tried changing the st.termname to xst-256color and that didn't work either, in fact it was causing more issues with crashing vim. Opacity seems to work on master but not 0.8.4. Cursor blink does not seem to work on anything but 0.7.2

**Comment by vikigenius** [comment]
In fact upon further testing cursorshape seems to have no effect at all

**Comment by actionless** [comment]
i see cursor shape changes with USR1 but for some reason indeed not applied when starting a new terminal instance, i'll check why

**Comment by vikigenius** [comment]
@actionless Thanks for the fix. Would it be possible to get this into the latest release ?
