### ISSUE TITLE
Italic fonts: separate setting in X resources? 

### ISSUE THREAD

**Issue by pellettiero** [gnotclub/xst#13]
Hi, is it possible to somehow expose a way in `.Xresources` to set separate fonts for italic, (perhaps italic bold and bold too)? 

Thanks

**EDIT:** found a patch for st which could have useful elements for this change: https://github.com/ericpruitt/edge/blob/master/patches/st-00-font-array-support.diff
This implements a fonts array support e.g. for chars not present in current .Xresources font.
Maybe this can help, cheers

**Comment by PeterGottesman** [comment]
I will take a look at this patch when I get a chance.

**Comment by befedo** [comment]
Is there an option to set italic fonts in `.Xresources`? Like `st.bold_font: 1` does?

**Comment by pellettiero** [comment]
@neeasade, @PeterGottesman I realized that this request may be too pretentious and it doesn't actually go well with the minimalism of `(x)st`, but I would like to know what do you two think about it, please.

Thank you!

**Comment by PeterGottesman** [comment]
@pellettiero, sorry I completely forgot about this. I will look at the patch tonight/this weekend. I am not sure about @neeasade's opinion on it when it comes to minimalism, but I will work on it unless he says something else.

**Comment by pellettiero** [comment]
Thanks!

**Comment by actionless** [comment]
starting from 0.8.4 there is Xresources option for italic fonts, mirroring same one for bold fonts
