### ISSUE TITLE
[Enhancement] Sixel support

### ISSUE THREAD

**Issue by Ramiferous** [gnotclub/xst#132]
I would love to have `sixel` support for `st/xst`. I've see a couple [fork](https://github.com/galatolofederico/st-sixel) of a [fork](https://github.com/charlesdaniels/st) which is a few years old now but could be resurrected. 

Besides just generally `sixel` support being standard and awesome, the specific reason I want this is because I left xterm a while back for `xst` (thanks, it's awesome!) and am now somewhat involved in the development of [clifm](https://github.com/leo-arch/clifm) which uses [lsix](https://github.com/hackerb9/lsix) for image previews. 

This all came about in [r/NetBSD](https://www.reddit.com/r/NetBSD/comments/oc02af/clifm_the_noncurses_file_manager_was_just_ported/) if you care to follow. 

Cheers :)

**Comment by actionless** [comment]
dup of https://github.com/gnotclub/xst/issues/47

**Comment by Ramiferous** [comment]
> 
> 
> dup of #47

My bad, cheers.
