### ISSUE TITLE
add undercurls support

### ISSUE THREAD

**Issue by RaafatTurki** [gnotclub/xst#136]
Undercurls are great because they are independent from the characters underneath them, which makes them very useful for hinting hints, warns, errs ..etc

This was originally a [kitty only](https://sw.kovidgoyal.net/kitty/underlines/) feature and then it was standardized as a specification and now most other terminals do support it.
Luckily this was already implemented into st as a [patch](https://st.suckless.org/patches/undercurl/) by HexOctal

here's how it looks like for both kitty and xst right now

### kitty
![image](https://user-images.githubusercontent.com/16624558/143937395-95864e9c-60ba-425c-8b72-a250106f4390.png)

### xst
![image](https://user-images.githubusercontent.com/16624558/143937493-c6b8182a-0e6e-4d38-971a-668a13658b86.png)

**Comment by actionless** [comment]
i think `UNDERCURL_STYLE` should be exposed to xresources, in case if you'll be submitting a PR

other than that i dont have any objections for this idea
