### ISSUE TITLE
[Request] OSC patch for easy theming? 

### ISSUE THREAD

**Issue by pfr-dev** [gnotclub/xst#138]
Would it be worth adding the [OSC patch](https://st.suckless.org/patches/osc_10_11_12_2/) for easy theming with [theme.sh](https://github.com/lemnos/theme.sh) etc?

**Comment by actionless** [comment]
i guess patch would require some adaptation to work together with xresources

**Comment by pfr-dev** [comment]
> i guess patch would require some adaptation to work together with xresources

I did wonder if they would work together or not.

**Comment by actionless** [comment]
why they wouldnt?

**Comment by neeasade** [comment]
note: OSC sequences have been added upstream in the release, which happened over the holidays. soon:tm:
