### ISSUE TITLE
Text cut off on sides 

### ISSUE THREAD

**Issue by plasticmae** [gnotclub/xst#14]
Parts of or entire characters are cut off on the left and right side of the window.

**Comment by PeterGottesman** [comment]
Can you link a screenshot and your .Xresources?

**Comment by gigavinyl** [comment]
Here is the [screenshot](http://i.imgur.com/OQYkrRO.png) (the far left hexagon icon is cut off).
and the .Xresources:
```
*.font: Gohufont:size=12:antialias=false
st.borderpx: 0

! special
*.foreground:   #aeb1b7
*.background:   #212121
*.cursorColor:  #c8cbce

! black
*.color0:       #3c3e42
*.color8:       #4f5558

! red
*.color1:       #dd6880
*.color9:       #de889a

! green
*.color2:       #83b879
*.color10:      #99c490

! yellow
*.color3:       #dec790
*.color11:      #e7d09a

! blue
*.color4:       #95b5e4
*.color12:      #a0beea

! purple
*.color5:       #c1a3e0
*.color13:      #cbacea

! cyan
*.color6:       #64c1d4
*.color14:      #88d1df

! white
*.color7:       #9a9da3
*.color15:      #b4b7bb


```

**Comment by PeterGottesman** [comment]
Can you also paste me your $PROMPT?

**Comment by gigavinyl** [comment]
@PeterGottesman My $PROMPT is: `%1{%(?.%F{white}▲%f.%F{magenta}△%f)%} %F{blue}%3~%f` and no, I'm in bspwm but if i remember correctly, the same issue was occurring in XMonad as well back when I used it.

**Comment by PeterGottesman** [comment]
Okay, thanks. 
I can't look into it right now, but I am at the very least able to reproduce it. I will take a closer look this weekend and get back to you.

**Comment by neeasade** [comment]
-> https://github.com/gnotclub/xst/issues/27
