### ISSUE TITLE
`xst` is behind `st`. Is this project still maintained?

### ISSUE THREAD

**Issue by pfr-dev** [gnotclub/xst#142]
Just wondering if `xst` is still maintained as `st` has been at `v0.8.5` since early Jan and `xst` is still on `v0.8.4` and hasn't been updated for over 18 months.

Cheers

**Comment by carlitos777** [comment]
+1

**Comment by neeasade** [comment]
> is this project still maintained 

yes-ish. I check upstream every 6 months or so

Thanks for the bump, all that has to happen is a `git pull git://git.suckless.org/st` + conflict resolution (and then some light testing). This will happen when the stars align ⭐ 🌟 .

**Comment by pfr-dev** [comment]
Cool thanks! I only ask because the `xst` package on NetBSD is maintained by [pin](https://codeberg.org/pin/) who tends to drop packages if they're not regularly updated. I think he needs regular releases in order to update the package in `pkgsrc`. I only bumped this thread because I use `xst` on my NetBSD machine and didn't want it to get dropped from his _'portfolio'_ :)

**Comment by 0323pin** [comment]
> xst package on NetBSD is maintained by pin who tends to drop packages if they're not regularly updated.

This has been updated now and when a new release becomes available, the package will be updated.

> I think he needs regular releases in order to update the package in pkgsrc

I try to avoid _git-HEAD_ builds in the main branch, yes.

**Comment by neeasade** [comment]
Tracking thoughts/path to a 0.8.5 tag here for transparency: https://github.com/gnotclub/xst/issues/145. I have some time off through the next week, so this will likely get some love.
