### ISSUE TITLE
Add more shortcuts

### ISSUE THREAD

**Issue by RaafatTurki** [gnotclub/xst#146]
As you know terminals can't really understand every keypress due to historical limitations.

However modern terminals (kitty, Alacritty, iTerm2 .. etc) don't abide by that and use the full range of keyboard shortcuts. more about this topic [here](http://www.leonerd.org.uk/hacks/fixterms/)

An [st patch](https://st.suckless.org/patches/fix_keyboard_input/) has already been cooked for this a while back and it only edits `config.def.h`

The catch is making it user configurable (opt-in preferably). As I'm sure not all users want all the new bindings.
for example currently `Ctrl [` is interpreted as `Esc` and I'm sure some users have that mapping ingrained into their muscle memory.

An another thing is [this PR](https://github.com/gnotclub/xst/pull/122) @neeasade was working on. idk if it's abandoned or if it would make this patch obsolete?

**Comment by neeasade** [comment]
This project is only concerned with upstream compat re: terminal keypress protocols. Aside from that, the only one I'm interested in is kitty's protocol. I would love it st becomes compatible with the kitty protocol or a patch were to surface for that, but would recommend just using kitty itself. 

The linked PR I had /could work/ as a shim for the linked patch, but the intent was for application level presses, not sending term-keys

**Comment by RaafatTurki** [comment]
I see, you must be talking about [this](https://github.com/kovidgoyal/kitty/issues/3248).

> or a patch were to surface for that  

How realistic do you recon implementing this would be

**Comment by neeasade** [comment]
> I see, you must be talking about https://github.com/kovidgoyal/kitty/issues/3248.

correct

> How realistic do you recon implementing this would be

not realistic -- I've seen it discussed upstream on occasion, but I do not think they are interested in incorporating it

**Comment by actionless** [comment]
if there is some elegant way to implement it as an *optional* behavior - then i think why not, we could merge it?

**Comment by RaafatTurki** [comment]
If there's no merge block I'd take a stab at it but, I'll need someone to show me an example of how to making it `xrdb` configurable since we can't just apply the patch as is and stick all that into `config.def.h`

**Comment by actionless** [comment]
mb wait for @neeasade if he also dont mind this, as i'm not sure from his replies above

**Comment by neeasade** [comment]
I'm rather not interested in this, both for the caveats listed in the st patch page and the fixterms tradeoffs mentioned at the bottom of the kitty protocol documentation: https://sw.kovidgoyal.net/kitty/keyboard-protocol/#fixterms-bugs

Having a PR for reference is always welcome though

> if there is some elegant way to implement it as an optional behavior 

re what "elegant" means to xst, it means small/isolated diffs where possible, to ease future merges with upstream st

> I'll need someone to show me an example of how to make it xrdb configurable since we can't just patch config.def.h and call it a day.

The USR1 signal calls this function: https://github.com/gnotclub/xst/blob/293b895061ac52ceb8eeef15d6447a917cf5ccd9/xst.c#L27. Handling would need to be added there to reset the keymapping somehow
