### ISSUE TITLE
Keyboard select patch

### ISSUE THREAD

**Issue by Barbaross93** [gnotclub/xst#149]
Is there was any interest in including the [keyboard-select](https://st.suckless.org/patches/keyboard_select/) patch with `xst`?

**Comment by actionless** [comment]
why not just use tmux instead of re-implementing all that logic anew?

**Comment by Barbaross93** [comment]
Because it doesn't make sense to start a new tmux session with every new terminal?

By that logic, why bother including a way to parse urls with `dmenu` and `xurls` when we could just do this with tmux:
```
bind-key u capture-pane \; save-buffer /tmp/tmux-buffer \; run-shell "xurls /tmp/tmux-buffer | dmenu"
```

**Comment by actionless** [comment]
> By that logic, why bother including a way to parse urls with dmenu and xurls when we could just do this with tmux:

i am agree, that feels also not necessary for terminal emulator

**Comment by Barbaross93** [comment]
Ok, I guess there is no interest here.

Thanks for the response.

**Comment by actionless** [comment]
i only left my opinion, mb @neeasade would like it

**Comment by neeasade** [comment]
> i only left my opinion, mb @neeasade would like it

I agree, leaving it to the tmux users

> By that logic, why bother including a way to parse urls with dmenu and xurls when we could just do this with tmux

This is more an accident of history when I was using xst as my terminal emulator and wanted that bind -- xresources bindings may enable configuring it in a more sensible place in the future
