### ISSUE TITLE
add reflow support

### ISSUE THREAD

**Issue by RaafatTurki** [gnotclub/xst#150]
The st terminal doesn't reflow text on terminal size change (which happens a lot on a tiling wm) and simply cut away the content.

I couldn't find a reflow patch on the official suckless site but I've found [this reddit post](https://www.reddit.com/r/unixporn/comments/qtzdnw/st_patch_for_vertical_and_horizontal_reflow_with/), The person behind that has actually extracted [this patch](https://github.com/BeyondMagic/flarity/blob/master/.patches/columns-rows-reflow-st-unpatched-new.patch) from this [st fork](https://github.com/ashish-yadav11/st)

I think this patch should be applied by someone who knows the xst source better than I do, reflowing should make a fine addition to xst.

**Comment by actionless** [comment]
why not just using tmux though? 🤔

**Comment by RaafatTurki** [comment]
@actionless This solution is niche, overkill, and a crutch that comes with many issues:

- Is it feasible to launch a new tmux session per xst terminal?
- Does tmux reflow the same way normal reflows (not mess with TUIs and the like)?
- Sometimes I need to open `tmate` or other cli tools that use `tmux` within, I will have to deal will nesting tmux session in such case.
- `$TERM` will be set to `screen-256color` instead of the normal `xst-256color` losing all xst features (like undercurls)
- Care will have to be taken regarding separating the `tmux` keybinds and any other TUIs used within

I'm sure there are more points to this that would arise when this solution is put to practice.

**Comment by RaafatTurki** [comment]
I think we're deviating from the subject here, this issue is about the reflow patch, not tmux.

I don't want to use tmux the way you're suggesting and I believe most users would agree w me, The points I've provided were illustrative of what users (including myself) would need to go through just to get their terminal to reflow according to your solution.

**Comment by actionless** [comment]
i am still not convinced - i see point adding features which could be done ONLY on the level of terminal itself, but if it's smth could be done in a terminal multiplexer/shell/other app - i personally prefer keeping terminal to do only minimal required job. other maintainers may not agree with me, so i'll leave the discussion open, until we'll have some generic policy on such sort of features

**Comment by wael444** [comment]
https://st.suckless.org/patches/scrollback/st-scrollback-reflow-0.8.5.diff

:)

**Comment by RaafatTurki** [comment]
> https://st.suckless.org/patches/scrollback/st-scrollback-reflow-0.8.5.diff

I didn't know that existed, This simplifies a lot since scrollback is already patched.
@neeasade @actionless I need the green light to PR this in.

**Comment by neeasade** [comment]
that's a big patch. going to echo @actionless and say if you want reflow in xst, use tmux (thank you for the interest and linking it thouguh)
