### ISSUE TITLE
`st-256color` as termname giving errors

### ISSUE THREAD

**Issue by crzjp** [gnotclub/xst#154]
Running xst from Void Linux repository, version (`xst -v`):

```
xst 0.8.4
```

Setting `st-256color` as `st.termname` outputs errors when startup:

```
warning: Could not set up terminal.
warning: TERM environment variable set to 'st-256color'.
warning: Check that this terminal type is supported on this system.
warning: Using fallback terminal type 'xterm-256color'.
```

Also when pressing `ctrl + l` to cleaning the terminal:

```
'st-256color': unknown terminal type.
```

Am I missing something?

**Comment by neeasade** [comment]
Does `xst-256color` give the same error?

**Comment by crzjp** [comment]
Don't, but i'm setting this value to get better compatibility, like different cursors to vi-mode on fish shell. It has a list of terminals to check and st is in, but not xst.

By this, I know it might be a fish related issue, but I think it can interest xst devs since `st-256colors` should be a valid value.

**Comment by neeasade** [comment]
> since st-256colors should be a valid value.

xst provides only `xst-*` terminfo items (IIRC the issue I previously ran into was that ncurses shipped conflicting `st-*` terminfo entries). 

You might also install vanilla st or some other program that provides st terminfo

FWIW I'm not seeing the term error on startup here:

![shot](https://user-images.githubusercontent.com/3747396/219870395-aef0b7cf-937c-4148-85e1-46230870d6d4.png)

I did see a specific reference to backspace handling [here](https://github.com/fish-shell/fish-shell/blob/4a1a59c5a80e0f6d391736b3bd94d8a4862cc1ce/share/functions/fish_default_key_bindings.fish#L96) in fish as well

**Comment by crzjp** [comment]
> You might also install vanilla st or some other program that provides st terminfo

Installed the `st-terminfo` package and fixed the issue, just like you said. Now, the cursors and keybinding works pretty well. Thank you for the attention
