### ISSUE TITLE
Works but getting odd output in terminal launched from

### ISSUE THREAD

**Issue by chopfitzroy** [gnotclub/xst#16]
So I have run `./st` after running `make` and it opens up and works but when I interact with the terminal I get endless lines of this:
```
erresc(default): gfx attr 10 unknown
ESC[0;10m
```
*This is from the terminal I ran `./st` in?

**Comment by pellettiero** [comment]
> Running st
> ----------
> If you did not install st with `make clean install`, you must compile
> the st terminfo entry with the following command:
> 
>     tic -sx st.info
> 
> See the man page for additional details.

(Taken from the main README of st)

I'm assuming you didn't install it with make, you're not supposed to use st without the above if you don't plan on installing it.
Could you please try again?
