### ISSUE TITLE
[PATCH] Add the themed_cursor patch

### ISSUE THREAD

**Issue by toniz4** [gnotclub/xst#162]
Currently, xst uses a basic bitmapped mouse cursor coming from `XDefineCursor`. This makes xst inconsistent with other applications that uses the same cursor configured by Xorg.

[themed_cursor](https://st.suckless.org/patches/themed_cursor/) fixes this by using libXcursor to load the cursor, this makes it consistent with the rest of the desktop environment. Plus you can also configure the cursor shape to use.

If it's of interest, I can submit a PR. Making it possible to configure the cursor shape via Xresources.

**Comment by actionless** [comment]
i can't reproduce an issue at first place - when i hover cursor over xst it looks the same as over this field in which i'm typing the reply in Firefox (and also dpi-scaled)

**Comment by toniz4** [comment]
Thats weird, could be differences in the X11 configuration. What DE/WM are you using?

Here xterm, xst and st all share the same problem. They use the default X11 cursor, and it's not scaled.

**Comment by actionless** [comment]
AwesomeWM, but in Openbox it also seems to be ok

**Comment by toniz4** [comment]
> AwesomeWM, but in Openbox it also seems to be ok

Same here. Closing since it's probably a problem with my X configuration.

**Comment by actionless** [comment]
i have a symlink `~/.icons/default -> /path/to/my/cursor_theme`, without it cursor acts funny under AwesomeWM in many apps, idk though if particularly with xst
