### ISSUE TITLE
Add an icon [PLEASE SUBMIT ICON SUGGESTIONS]

### ISSUE THREAD

**Issue by parchd-1** [gnotclub/xst#20]
Any chance of adding an icon with the _NET_WM_ICON hint?
Consider it a low priority feature request to make alt-tabbing less ugly :wink:

**Comment by neeasade** [comment]
probably good idea -- there's some options in CC maybe like this one. https://thenounproject.com/search/?q=terminal&i=871427

**Comment by sroracle** [comment]
If you're curious on how to patch this in the meantime, check out [this patch](https://github.com/sroracle/patches/blob/master/x11-terms/st/icon.patch) that I adapted from [here](https://github.com/defiant-labs/sta/blob/master/patches/st-themes_xicon.diff). The icon in my patch is from [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/48x48/apps/utilities-x-terminal.svg).

**Comment by butyoutried** [comment]
There is now [netwmicon](https://st.suckless.org/patches/netwmicon/) patch.

**Comment by actionless** [comment]
please propose icon candidates with matching license or your personal design (which is more fun so more preferred 😸)
