### ISSUE TITLE
Wide characters are cut off

### ISSUE THREAD

**Issue by cherryman** [gnotclub/xst#27]
![2017-05-07-111957_467x206_scrot](https://cloud.githubusercontent.com/assets/15808018/25782356/43e2ae8e-3317-11e7-9689-7b48f5c7f673.png)

Any way to fix this?

**Comment by dab** [comment]
any updates on this issue? 
thanks.

**Comment by actionless** [comment]
your issue report could be improved by providing font used, text string and expected result (in which terminal it works as expected)

**Comment by mustaqimM** [comment]
I also face the same problem, though I only use a unicode glyph in one place:
![image](https://user-images.githubusercontent.com/24436622/61102970-bd857800-a45f-11e9-890b-054a2af6874b.png)
If I add 2 spaces to the place I'm defining it:
```zsh export ZSH_PLUGINS_ALIAS_TIPS_TEXT=$'\033[01;33m💡  '```, then it outputs correctly.

![image](https://user-images.githubusercontent.com/24436622/61103005-e60d7200-a45f-11e9-8082-f73751e4cb2c.png)

On `kitty` it shows as:
![image](https://user-images.githubusercontent.com/24436622/61103214-a3986500-a460-11e9-87b3-413715e12b44.png)

And on `alacritty`:
![image](https://user-images.githubusercontent.com/24436622/61103265-ce82b900-a460-11e9-85de-60dc8711cd62.png)

It occurs with any font. With or without escape chars.

**Comment by actionless** [comment]
weird, i can't reproduce this:
![2019-07-12--1562941679_397x123_scrot](https://user-images.githubusercontent.com/1655669/61135502-0a019f80-a4c2-11e9-988f-477c87fafdfa.png)

**Comment by mustaqimM** [comment]
hmm, I've tried:
```zsh
Iosevka
DejaVu Sans Mono
Noto Sans Mono
Liberation Mono
FreeMono
Monofur Nerd Font
Nimbus Mono L
```
And all require two spaces after the glyph to render correctly. What emoji font are you using? I have `noto-fonts-emoji-20180810` & `twemoji`

![image](https://user-images.githubusercontent.com/24436622/61144888-ada07f00-a4c5-11e9-818d-e80c55571e5c.png)

**Comment by actionless** [comment]
```
  <family>monospace</family>
  <prefer>
   <family>Fantasque Sans Mono</family>
   <family>Emoji One Color</family>
</prefer>
```

**Comment by actionless** [comment]
but with different monospace fonts it also works, so i guess the problem is with emoji font, what it's not setting what chars should be double-width:

![2019-07-12--1562951740_470x168_scrot](https://user-images.githubusercontent.com/1655669/61146125-8bb0f780-a4d9-11e9-8d6e-b4d6cc0bd70b.png)

**Comment by mustaqimM** [comment]
I think there are 2 problems here:
`noto-fonts-emoji` requires 2 spaces. `twemoji`(the successor to Emoji One) needs 1 space but only on `st`.

On alacritty and kitty, it shows correctly without a space. (I tried it with `twemoji` and `font-symbola`). But st needs the space. Presumably because it's placing a two cell width char in a single cell

**Comment by actionless** [comment]
because your double-width are loading not directly from your font, but from the font's fallback, you need to manually add that fallback font to font_fallback section and set appropriate font size to adjust the width, see the guide here: https://github.com/gnotclub/xst/wiki/Color-Emojis
