### ISSUE TITLE
xst doesn't care about my bold font settings

### ISSUE THREAD

**Issue by Hund** [gnotclub/xst#32]
I don't like bold font, so with URxvt I solved it with `URxvt.boldFont:xos4terminus:size=12`. But xst doesn't care that I use a non-bold font setting (`st.boldFont:xos4terminus:size=12`) and uses bold fonts anyway.

I know I can set `static int bold_font` to `0` to disable bold fonts, but that also disables the colors for the bold fonts. Things like emerge uses bold fonts, which results in emerge showing pretty much everything in orange.

![stboldcolors](https://user-images.githubusercontent.com/320498/29744394-56e217d8-8aa4-11e7-9b24-8fbf073cd469.png)

Anyway around this? :)

**Comment by actionless** [comment]
i can't reproduce it

**Comment by actionless** [comment]
could you share your particular test script you used for colors? mb it's using some other escape sequences than mine

**Comment by actionless** [comment]
run `xst` from other terminal and see if writes anything to stderr

**Comment by alanpearce** [comment]
Same here. I used `msgcat --color=test` from the `gettext` package, but it's reproducible with anything that sets bold, including the prompt I'm using ([agkozak](https://github.com/agkozak/agkozak-zsh-prompt))

Running `st` from a terminal (it doesn't seem to be installed as `xst`, at least on NixOS) yields:

> st: font weight does not match
> st: font slant does not match
> st: font weight does not match
> st: font slant does not match
> st: font weight does not match
> st: font weight does not match

![image](https://user-images.githubusercontent.com/850317/65317690-9dc7aa00-db9c-11e9-83d8-f15e099c0934.png)

`xrdb -query` (I use default colours, which work across terminals):
```
*.font:                   -xos4-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*
*background:              #ffffff
*color0:                  #ffffff
*color1:                  #c82829
*color10:                 #718c00
*color11:                 #eab700
*color12:                 #4271ae
*color13:                 #8959a8
*color14:                 #3e999f
*color15:                 #1d1f21
*color16:                 #f5871f
*color17:                 #a3685a
*color18:                 #e0e0e0
*color19:                 #d6d6d6
*color2:                  #718c00
*color20:                 #969896
*color21:                 #282a2e
*color3:                  #eab700
*color4:                  #4271ae
*color5:                  #8959a8
*color6:                  #3e999f
*color7:                  #4d4d4c
*color8:                  #8e908c
*color9:                  #c82829
*cursorColor:             #4d4d4c
*foreground:              #4d4d4c
URxvt.boldFont:           -xos4-terminus-bold-r-*-*-12-*-*-*-*-*-iso10646-*
URxvt.fading:             0
URxvt.geometry:           100x40
URxvt.intensityStyles:    true
URxvt.letterSpace:        0
URxvt.lineSpace:          2
URxvt.pointerBlank:       true
URxvt.pointerBlankDelay:  987654321
URxvt.saveLines:          16384
URxvt.scrollBar:          false
URxvt.scrollTtyKeypress:  true
URxvt.scrollTtyOutput:    false
URxvt.scrollWithBuffer:   true
URxvt.scrollstyle:        plain
URxvt.secondaryScroll:    false
URxvt.urgentOnBell:       true
st.bold_font:             0
st.borderpx:              1
st.chscale:               1.2
st.mouseScrollLines:      3
```

**Comment by alanpearce** [comment]
`st.bold_font:1` makes the colours correct, but there's no bold font and I don't see a setting for it.

**Comment by actionless** [comment]
are you sure you're running an up-to-date `xst` app?

**Comment by actionless** [comment]
see also https://github.com/gnotclub/xst/pull/52

**Comment by alanpearce** [comment]
I was on 0.7.1; 0.7.2 seems to work :tada:
