### ISSUE TITLE
file owned by 'xst-git'

### ISSUE THREAD

**Issue by knstl** [gnotclub/xst#33]
I'm not sure what the issue is here.  This is the output of any pacman related command with xst-git from AUR installed.

error: file owned by 'ncurses' and 'xst-git': 'usr/share/terminfo/s/st'
error: file owned by 'ncurses' and 'xst-git': 'usr/share/terminfo/s/st-256color'

**Comment by neeasade** [comment]
The issue is ncurses provides st termcap definitions, which conflict with xst as it never changed the name.

Perhaps we can change the name (and then the TERM names) to xst-*..

**Comment by Soren-Nordstrom** [comment]
I suppose in the meantime it's not causing any failures, it's just an eyesore.

**Comment by actionless** [comment]
is anyone going to work on that?
otherwise i could submit a PR (for this and #36)

**Comment by laserswald** [comment]
Go for it, @actionless.
