### ISSUE TITLE
binary name

### ISSUE THREAD

**Issue by rapha8l** [gnotclub/xst#36]
Hi,

Would you consider calling the binary xst in order to have both xst and st ?
Thanks

**Comment by neeasade** [comment]
This would fix https://github.com/neeasade/xst/issues/33 if we also bumped terminfo definitions as well at least.

**Comment by rapha8l** [comment]
It would be nice, thanks !

**Comment by neeasade** [comment]
But would also break anyone currently relying on `st` binary name.

**Comment by rapha8l** [comment]
It would not be the first project to change its name, and binary name :-)
If you advertise it, people will get it eventually, but it's up to you
