### ISSUE TITLE
Make it possible to specify multiple (fallback) fonts

### ISSUE THREAD

**Issue by novcn** [gnotclub/xst#41]
With URxvt you can configure your font:

```
URxvt.font: font1,font2
```
And `font2` glyphs will be used as fallback if `font1` doesn't provide them. This is useful for displaying icon fonts like https://github.com/stark/siji

It would be nice if xst could do this.

**Comment by mustaqimM** [comment]
@novcn @arkhan Put something like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<fontconfig>
  <!--
  Make FantasqueSansMono Nerd Font the initial fallback font for Iosevka Medium
  -->
<match>
    <test name="family"><string>Iosevka Medium</string></test>
    <edit name="family" mode="append" binding="strong">
      <string>FantasqueSansMono Nerd Font</string>
    </edit>
  </match>
```
in `~/.config/fontconfig/fonts.conf`

Before:
https://i.imgur.com/d0JIsFg.png
After:
https://i.imgur.com/ogYvoJg.png

**Comment by neeasade** [comment]
note: we could do this with https://st.suckless.org/patches/font2/, then split on ',' for xresource loading

**Comment by RaafatTurki** [comment]
update?

**Comment by actionless** [comment]
@RaafatTurki PRs welcome ;)

**Comment by BeyondMagic** [comment]
Not sure how font2 loads the fonts, but I'll give it a look and see if it can be done by XResource easily.

**Comment by BeyondMagic** [comment]
It took longer than what I thought it would, but to be honest, it works just fine. The way I implemented it actually uses the font2's fonts of the config.h as well and add the ones from XResources with it.

I'll make a PR if @gnotclub is willing to accept it.

**Comment by actionless** [comment]
thanks in advance!
