### ISSUE TITLE
Borderpx = 0 doesn't apply to terminal

### ISSUE THREAD

**Issue by tuyenpm9** [gnotclub/xst#49]
I have this set in both `st` and `xst` `static int borderpx = 0;`

`st` works - I have tmux session and the left status in bottom of screen

`xst` doesn't work - tmux session's status is a little above my screen, I can move cursor under the tmux's left status.

**Comment by actionless** [comment]
is it working when you setting it via Xresources?

**Comment by tuyenpm9** [comment]
@actionless : I set it both places, doesn't affect either.

**Comment by tuyenpm9** [comment]
Due to font didn't appear correctly.
