### ISSUE TITLE
Apply st-relativeborder patch, redundant spaces at bottom screen

### ISSUE THREAD

**Issue by tuyenpm9** [gnotclub/xst#50]
I raised a question in here https://unix.stackexchange.com/questions/472800/st-terminal-shrink-of-bottom-bar-because-of-font-with-small-size

Look at st's patches, I think this might be the right patch to fix this issue, unfortunately it failed even with original st-0.8.1. Probably won't work on xst.

Does xst come with idea of fix this issue?

**Comment by actionless** [comment]
but what is the issue?

imagine your screen height is 11 pixels

your font size set to 2 pixels

you have 1 pixel border at the bottom because screen height is not dividable by font height?

**Comment by tuyenpm9** [comment]
Make sense, so I have adjust the font size or have to live with it? :)

**Comment by actionless** [comment]
if your terminal is always the same size — yes

for floating mode there are WM hints (which suggesting height to be dividable by font height) but i think it's not implemented in st/xst (AFAIK it should be in xterm and some other popular terminals, you can try if it works there as expected or not)

**Comment by tuyenpm9** [comment]
My terminal is alwasy the same size.

Yes, I can see other terminals implemented it. Would st/xst implement this feature?

**Comment by tuyenpm9** [comment]
Okay then I'll check X and resize term manually.
