### ISSUE TITLE
[Q] Only change cursor's shape to '|' when over text

### ISSUE THREAD

**Issue by tuyenpm9** [gnotclub/xst#57]
I think this behavior that xst can achieve, keep cursor's shape and only change to `|` when over text to prapare to select.

**Comment by actionless** [comment]
i think you need to provide a bit more info if you want someone else to understand what's on your mind

**Comment by tuyenpm9** [comment]
I think I misunderstanding here but is it possible to channge cursor from `|` to something else by default?

**Comment by actionless** [comment]
do you mean this? https://github.com/gnotclub/xst/blob/master/doc/Xresources#L13-L14

**Comment by tuyenpm9** [comment]
Like this when not over text:
![Image of Yaktocat](https://s10629.pcdn.co/wp-content/pictures/2012/05/mouse-cursor-jumps.jpeg)

and become `|` when over text.

**Comment by actionless** [comment]
but terminal consist only of text

**Comment by tuyenpm9** [comment]
That's the thing, even on windows I can see this implementation. I assume that but in case I always use terminal in full mode and 90% working on terminal, having only `|` make me undistinguishable the mouse movement.

This is alter user experience I think. Weird that on always text editor I don't see any implementation, noone ever think about this?

**Comment by actionless** [comment]
because terminal consist only of text

**Comment by tuyenpm9** [comment]
So this is about visible chars vs spaces/tabs.

**Comment by actionless** [comment]
but none ontopic terminal or toolkit's textarea/input widget does that

however, if you'll implement it in a way what code which handles mouse coordinates won't be executing if option is disabled -- it could be agreeable

**Comment by tuyenpm9** [comment]
> however, if you'll implement it in a way what code which handles mouse coordinates won't be executing if option is disabled -- it could be agreeable

Not sure I understand your comment much. This might be minor issue but increase user experience somehow.

**Comment by actionless** [comment]
i mean , guard the code which will handle mouse coordinate changes with `if`, so it won't be executing if option is disabled

just use refresh rate loop and, to avoid slow downs, skip every 100 frames, that anyway will be fast enough for cursor state to change

**Comment by tuyenpm9** [comment]
Thanks for the hint, will think about if I have more spare time.

**Comment by tuyenpm9** [comment]
@actionless : Would you consider it as feature request? Or maybe not?

**Comment by actionless** [comment]
yeah, you can submit a pull request with such feature
