### ISSUE TITLE
-geometry doesn't work

### ISSUE THREAD

**Issue by tuyenpm9** [gnotclub/xst#60]
The same system, this command work: `urxvtc -name ArbitraryWindows -geometry 160x50`
output: windows is resized.

But with xst, it won't work: `xst -class=ArbitraryWindows -geometry=100x50`
no output, the result is that xst doesn't respect -geometry option that resize xst' window to something 100x50.

How to fix it?

**Comment by neeasade** [comment]
the argument here is -g (from the man page) -- eg `st -g 10x10`
