### ISSUE TITLE
Changing cursor shape in vim

### ISSUE THREAD

**Issue by vikigenius** [gnotclub/xst#63]
Hi, I am trying to change the shape of the cursor based on the mode in vim.

The wiki suggests to add this to my vimrc:

let &t_SI = "\\\<Esc>[6 q"
let &t_SR = "\\\<Esc>[4 q"
let &t_EI = "\\\<Esc>[2 q"

http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes

It specifically mentions st, so I tried it, but it doesn't work. Any idea why?

**Comment by vikigenius** [comment]
Yes

**Comment by actionless** [comment]
what kind of delay?

**Comment by vikigenius** [comment]
Oh, i don't think it's too much trouble. But changing from blinking block to blinking ibeam when I go from normal to insert is very quick, but going back to normal takes more time.

**Comment by actionless** [comment]
i think redraw should be tied to blinking rate or keypress

**Comment by masaeedu** [comment]
@vikigenius What did you do to get it working using the tmux escape sequence?

**Comment by iynaix** [comment]
@masaeedu Spent wayyyyyy too long trying to figure this out. I added `st.termname: st-256color` in my `.Xresources` and it works!

I may be completely wrong here, but my understanding is that st doesn't report the termcaps for cursor shape correctly. Vim has exceptions for such terminals and overrides their termcaps. Masquerading as st now allows vim to apply the fix.

**Comment by actionless** [comment]
in xst itself i have default value, `xterm-256color`, in `tmux` -- `screen-256color`

(if it would be helpful for anybody)


regarding caret shape in vim: https://github.com/actionless/dotfiles/blob/master/vim/.vim/caret_shape.vim
