### ISSUE TITLE
Update package for Fedora 29

### ISSUE THREAD

**Issue by k4pu77** [gnotclub/xst#64]
Hi all
I would like you to use `xst` in Fedora 29. The linked [copr repo](https://copr.fedorainfracloud.org/coprs/keefle/xst/) only contains builds up to Fedora 28. Could you create a build for Fedora 29?
Thanks and keep up the good work!

**Comment by actionless** [comment]
i guess you need to contact @keefle

**Comment by actionless** [comment]
sorry, @KmBKeef
