### ISSUE TITLE
Boxdraw patch

### ISSUE THREAD

**Issue by noamcore** [gnotclub/xst#66]
Hi, xst and st by default uses the font to print lines/blocks/braille characters, but some fonts seems weird.

![image](https://user-images.githubusercontent.com/44407744/53292935-bf4ce880-37a9-11e9-84e1-1a502e00d056.png)

[This patch](https://st.suckless.org/patches/boxdraw/) uses a custom rendering for a flaw, nice boxes.

![image](https://user-images.githubusercontent.com/44407744/53292948-7ea19f00-37aa-11e9-98a8-f560633cc6f9.png)

Can this patch be merged into the xst?

**Comment by actionless** [comment]
if it will be optional (and adjustable via xresources) -- 100 % no one will object to accept such change

**Comment by noamcore** [comment]
Yes. By default it is disabled. So I'll make a pull request to merge this one.

What resource name I give to xresources, `st.boxdraw` ?

**Comment by actionless** [comment]
don't have strong preference on name st.boxdraw looks fine :+1:
