### ISSUE TITLE
Clipboard patch

### ISSUE THREAD

**Issue by pinpox** [gnotclub/xst#67]
Hey,

thanks for the great work!
Would you mind adding the clipdoard patch too?

https://st.suckless.org/patches/clipboard/
Coping from the browser e.g. is quite hard without it and I suppose I would not break any other funcionality. If you like I can submit a PR.

Cheers,
Pablo

**Comment by actionless** [comment]
i see it require some additional steps to fully work for an end-user:

> You may want to replace selpaste with clippaste in your config.h to complete the affect.


what do you think about implementing single option (also in xst Xresources config) which will be not only enabling new behavior but also doing selpaste/clippaste thing?

**Comment by neeasade** [comment]
we currently have clippaste/selpaste under the default bindings, Ctrl+Alt+V and Ctrl+Alt+Y -- we have the clipboard patch as well. maybe this can be closed then?

**Comment by RaafatTurki** [comment]
I'd like to be able to configure the key bindings for this through the Xresources patch.
