### ISSUE TITLE
incorrect Xresouses colors

### ISSUE THREAD

**Issue by zakariaGatter** [gnotclub/xst#68]
When i change the colors and reload, st use a different colors 

my config file 
```
#include ".xcolors/xcolors"
! ST SETTINGS {{{
! These are all possible options, presented with default values.
! xst will fallback to *.option if st.option is not present.
! see src/config.h for more information about option meanings.

! These options only take effect on startup.
st.termname:     st-256color
! if you do not set shell, precedence is: -e arg, utmp option, SHELL env var, /etc/passwd shell
st.shell:        /bin/sh

! The following options options can be reloaded via USR1 signal.
st.font:              Terminus:size=10:antialias=true:autohint=true;
st.borderpx:          10
! Available cursor values: 2 4 6 7 = █ _ | ☃ ( 1 3 5 are blinking versions)
st.cursorshape:       2
! thickness of underline and bar cursors
st.cursorthickness:   2
! 0: normal blinking, 1: leave cursor border and blink with cursors background
st.cursorblinkstyle:  1
! 0: cursor blinks with a constant interval; 1: blinking cycle resets on key input
st.cursorblinkontype: 1
st.bold_font:         0
st.xfps:              120
st.actionfps:         30
! Amount of lines scrolled
st.mouseScrollLines:  1
! Kerning / character bounding-box height multiplier
st.chscale:           1.0
! Kerning / character bounding-box width multiplier
st.cwscale:           1.0
! blinking timeout for terminal and cursor blinking (0 disables)
st.blinktimeout:      800
! bell volume. Value between -100 and 100. (0 disables)
st.bellvolume:        100
! this is a char that is exposed like so: `printf '\033[z'`
st.prompt_char:       $
! This option is can be preedit style. Available values: `root` `overthespot` (Default taken `root`)
st.imstyle:           root

! opacity==255 means what terminal will be not transparent, 0 - fully transparent
st.opacity:      255
! }}}
```

xcolor file 
```
! special
*.foreground:   #7fc3d3
*.background:   #263137
*.cursorColor:  #7fc3d3

! black
*.color0:       #545454
*.color8:       #545454

! red
*.color1:       #455964
*.color9:       #455964

! green
*.color2:       #424b6c
*.color10:      #424b6c

! yellow
*.color3:       #747474
*.color11:      #747474

! blue
*.color4:       #1ca5c5
*.color12:      #1ca5c5

! magenta
*.color5:       #6c4262
*.color13:      #6c4262

! cyan
*.color6:       #8abeb7
*.color14:      #8abeb7

! white
*.color7:       #707880
*.color15:      #c5c8c6
```

**Comment by actionless** [comment]
is it working for you after removing the dots from the variable names?

**Comment by zakariaGatter** [comment]
ohhhh thank you it work perfect now when i remove the dots

**Comment by actionless** [comment]
@neeasade what was the expected behavior when you were implementing this?

**Comment by neeasade** [comment]
I had not tested sans dots, the intended behavior is eg `st.background` with a fallback to `*.background` -- I use `*.<color>` in my own Xresources[1], but I've never done the `#include <file>` thing.

[1] https://github.com/neeasade/dotfiles/blob/master/templates/Xresources#L24

**Comment by zakariaGatter** [comment]
> @neeasade what was the expected behavior when you were implementing this?

wrong color like background and forground and almost all colors

**Comment by zakariaGatter** [comment]
> @neeasade what was the expected behavior when you were implementing this?

all colors wrong like the background and foreground almost all

**Comment by actionless** [comment]
@zakariaGatter have you tried debugging `xrdb -query` output?

there is also possibility what your Xresources have different variable naming, so when you doing xrdb merge old settings are not overwritten

**Comment by zakariaGatter** [comment]
> @zakariaGatter have you tried debugging `xrdb -query` output?
> 
> there is also possibility what your Xresources have different variable naming, so when you doing xrdb merge old settings are not overwritten

i dont know if this possible but i tried `xrdb -query` and its show me the same color in the file 

maybe xst handle the color differently

but its ok i love xst anyway

**Comment by neeasade** [comment]
Tested color with an `#include` directive, works as expected (sets colors from last set *.* or st.* color)
