### ISSUE TITLE
Issue diskplay to font??

### ISSUE THREAD

**Issue by xmiah0906** [gnotclub/xst#69]
I using xst and same font with urxvt, I don't know issue xst about:

https://i.imgur.com/ewNvFvJ.jpg
The left is xst and middle is urxvt. 

Xresources config: 

> ! These options only take effect on startup.
> st.termname: st-256color
> ! The following options options can be reloaded via USR1 signal.
> st.font:                 Roboto Mono for Powerline:pixelsize=9:antialias=true:autohint=true \
>                                  Ubuntu Mono derivative Powerline for Powerline:pixelsize=9:antialias=true:autohint=true \
>                  Typicons:pixelsize=9:antialias=true:autohint=true:style=Book;
> 
> st.borderpx:     22
> ! Available cursor values: 2 4 6 7 = █ _ | ☃ ( 1 3 5 are blinking versions)
> st.cursorshape:  4
> st.cursorthickness:  2
> st.cursorblinkstyle: 0
> st.cursorblinkontype: 1
> st.bold_font:    0
> st.xfps:         120
> st.actionfps:    30
> st.chscale:      1.0
> st.cwscale:      1.0
> st.blinktimeout: 800
> st.bellvolume:  100
>

**Comment by actionless** [comment]
actually urxvt and xterm rendering fonts not so good

so please use some `vte`-based terminal or some gtk/qt application (read: with sane freetype2 support) as a reference and check if you still can reproduce the issue
