### ISSUE TITLE
cols and rows 

### ISSUE THREAD

**Issue by zakariaGatter** [gnotclub/xst#72]
i Compile xst on my Ubuntu 18.04 and i love it 

but i want to ask one question 

is there any way to change the __cols__ and __rows__ on xst from Xresources file with out recompiling it ???

**Comment by neeasade** [comment]
not in Xresources right now -- but you can on launch with the `-g` flag

**Comment by zakariaGatter** [comment]
i know but want something from Xresources 

but its ok thank u guys anyway
