### ISSUE TITLE
terminfo is in different folder than expected

### ISSUE THREAD

**Issue by andys8** [gnotclub/xst#78]
### Issue
After cloning the repository and running `sudo make install`.

> Please see the README file regarding the terminfo entry of xst.
> 6 entries written to /usr/local/share/terminfo

terminfo is copied to `/usr/local/share/terminfo`.
All other terminfo is in `/usr/share/terminfo`

### System

Mint 19.1 tessa, fish, version 3.0.2

### Result

```
<W> fish: Could not set up terminal.
<W> fish: TERM environment variable set to 'xst-256color'.
<W> fish: Check that this terminal type is supported on this system.
<W> fish: Using fallback terminal type 'ansi'.
bind: Key with name “ppage” does not have any mapping
bind: Key with name “npage” does not have any mapping
bind: Key with name “f1” does not have any mapping
bind: Key with name “ppage” does not have any mapping
bind: Key with name “npage” does not have any mapping
bind: Key with name “f1” does not have any mapping
bind: Key with name “ppage” does not have any mapping
bind: Key with name “npage” does not have any mapping
bind: Key with name “f1” does not have any mapping
```
(not sure if `xst-256color` or `st-256color` is the right choice)

But maybe this is expected or a system setting I'm not aware of :)

**Comment by DomHudson** [comment]
Hi @andys8 , why did you close this? I have the same problem - what is the solution?
Many thanks,
Dom

**Comment by neeasade** [comment]
@DomHudson You should be able to get around this by changing the PREFIX to /usr, ie `sudo make PREFIX=/usr install`

**Comment by andys8** [comment]
I closed this because I wasn't sure if it's my mistake and I started created an `st` fork myself so I wouldn't really be able to verify fixes or answer follow up questions. So I closed it to avoid bothering maintainers with it.

@neeasade Cool. Maybe it's worth adding these instructions to the README file.

**Comment by kevindirect** [comment]
I switched from a different build of st to xst and I couldn't get it to work properly without setting the termname to st-256color.
I installed it from the AUR, the PKGBUILD sets the PREFIX to /usr. In my case I don't know where xst-256color  (or xst's st-256color) is if it exists. I think ncurses is using an old terminfo file from my previous build of st. Anyone know where to find the terminfo file? My package manager isn't showing it and I couldn't find it in /usr/share/terminfo/x. Thanks

**Comment by actionless** [comment]
>  PKGBUILD runs make install instead of make clean install

fixed

**Comment by kevindirect** [comment]
For some reason terminfo files still aren't generated. I don't know why because the tic call is in the install target in the makefile and I have tic in my path. The readme says to make clean before installing which the PKGBUILD does. Everything works after running `sudo tic -sx st.info`.

> Running st
> ----------
> If you did not install st with make clean install, you must compile
> the st terminfo entry with the following command:
> 
>     tic -sx st.info
> 
> See the man page for additional details.

**Comment by actionless** [comment]
> terminfo files were generated by the PKGBUILD locally at ~/.terminfo/ instead of /usr/share/terminfo/

pkgbuild runs only `make` commands, so the Makefile should be fixed for that

**Comment by kevindirect** [comment]
I tested revision 11, it generates the terminfo files at /usr/share/terminfo. I had to delete existing xst terminfo files I generated with tic at /usr/share/terminfo to install with PKGBUILD.
