### ISSUE TITLE
Blinking cursor should be reset on keypress

### ISSUE THREAD

**Issue by mustaqimM** [gnotclub/xst#80]
Most other terminals do this including browsers. This is needed or else there's a point when typing and the cursor is completely hidden.

**Comment by actionless** [comment]
see https://github.com/gnotclub/xst/blob/master/doc/Xresources#L19-L20

**Comment by mustaqimM** [comment]
It's not quite the same, see kitty on the left:
https://streamable.com/kqmhh

xst still attempts to blink during key presses

**Comment by actionless** [comment]
i can't reproduce it, make sure you've applied the setting

**Comment by mustaqimM** [comment]
The setting is applied, it's much worse with it off.

**Comment by actionless** [comment]
although i still can't reproduce it
