### ISSUE TITLE
How to bind custom key

### ISSUE THREAD

**Issue by ztlevi** [gnotclub/xst#81]
Is there any way to define custom key in Xresources. 

For exmpale, for urxvt we could do
```
URxvt.keysym.Meta-c: eval:selection_to_clipboard
URxvt.keysym.Meta-v: eval:paste_clipboard
```

**Comment by hallabro** [comment]
Custom keys may be defined in your shell as well. See `bind -p` for `bash` and `bindkey` for `zsh`.

I guess it all depends on what you want to bind.
