### ISSUE TITLE
Spacing between window boarder and text.

### ISSUE THREAD

**Issue by kierun** [gnotclub/xst#83]
Is there a setting where I could make the boarder between the window and the start of the text smaller?

See screen shot:

![screenshot](https://user-images.githubusercontent.com/3079575/76292114-7bd6f680-62a6-11ea-8c39-9c71fce37784.png)

There seem to be a line or so around the text which makes the window a little bigger than it needs to be.

**Comment by actionless** [comment]
https://github.com/gnotclub/xst/blob/master/doc/Xresources#L12

**Comment by kierun** [comment]
@actionless Thank you. Curse Dyslexia!
