### ISSUE TITLE
Disabling blink timeout does not disable it completely

### ISSUE THREAD

**Issue by catzybluphish** [gnotclub/xst#84]
I'll have `st.blinktimeout: 0` in .Xresources and it indeed disables immobile blinking but it'll still blink every time when I move to another character. It's the most visible when you continously hold left/h or right/l on the start or end of a line respectively and the cursor will keep blinking at the pace of your input rate. Is there any way to stop it from blinking like that?

**Comment by actionless** [comment]
ah, i've just recalled what to turn off the blinking you need to choose an even cursorshape number instead of odd one: https://github.com/gnotclub/xst/blob/master/doc/Xresources#L13-L14
