### ISSUE TITLE
Handling OSC 52 escape codes

### ISSUE THREAD

**Issue by novcn** [gnotclub/xst#89]
Hey, I realized I was not able to copy / paste in tmux copy mode or emacs ([clipetty](https://github.com/spudlyo/clipetty)) while using xst.

The error I was receiving was
```
erresc: unknown str [52
```

This case is [handled in st](http://git.suckless.org/st/file/st.c.html#l1861) and after some quick hacking I was able to get tmux & emacs copy and paste working in xst.

Is this a known limitation to xst in combination with tmux and emacs?

Is this functionality pending the [upgrade to 0.8.X](https://github.com/gnotclub/xst/issues/82)?

I'd like to start contributing the project but need to get my bearings first as a new xst(/tmux/emacs) user.

**Comment by novcn** [comment]
This is closed by https://github.com/gnotclub/xst/issues/82

**Comment by neeasade** [comment]
@novcn still, thanks for reporting!
