### ISSUE TITLE
Disable bold, itatlic completely?

### ISSUE THREAD

**Issue by tmpm697** [gnotclub/xst#93]
xst version: 20200704.da50afd-1
os: archlinux up-to-date

With previous version `20190916.23e12ac-1` somehow `xst` doesn't support `bold` or `bold` didn't work for me when I build from `xst-git` but in the current version `20200704.da50afd-1` when an application want to have `bold` enable on, xst will correctly `bold` it, but I don't want to have `bold` or `italic` at all -- I don't want to support application to display `bold` and `italic`.

How can I force that with `xst`?

I saw that `config.h` has default disable `bold` and `italic`, and I have below lines in `config.h`
```
int disablebold = 0;
int disableitalic = 0;
```
why I can still set `bold` and `italic`?

**Comment by tmpm697** [comment]
How to test:
```
bold=$(tput bold)
normal=$(tput sgr0)
echo "this is ${bold}bold${normal} but this isn't"
```

**Comment by neeasade** [comment]
See https://github.com/gnotclub/xst#breaking-changes-with-084, set st.disablebold and st.disableitalic to 1 in .Xresources

**Comment by tmpm697** [comment]
Thanks @planet36
